apiVersion: apps/v1
kind: Deployment
metadata:
  name: cluster1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cluster1
  template:
    metadata:
      labels:
        app: cluster1
    spec:
      containers:
      - name: cluster1-container
        image: rabbitmq:3.6.8-management
        securityContext:
          privileged: true
        ports:
        - containerPort: 80