apiVersion: apps/v1
kind: Deployment
metadata:
  name: cluster2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cluster2
  template:
    metadata:
      labels:
        app: cluster2
    spec:
      containers:
      - name: cluster2-container
        image: rabbitmq:3.6.8-management
        securityContext:
          privileged: true
        ports:
        - containerPort: 80