apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    role: db
  name: db-b-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /var/lib/mysql_replica