apiVersion: v1
kind: Service
metadata:
  labels:
    role: web-rest
  name: web-rest-2
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 8002
    targetPort: 8002
    nodePort: 30082
  selector:
    app: web-rest-2