apiVersion: v1
kind: Service
metadata:
  labels:
    role: web-rest
  name: web-rest-1
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 8001
    targetPort: 8001
    nodePort: 30081
  selector:
    app: web-rest-1